# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breadcrumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('longitude', models.CharField(max_length=32)),
                ('latitude', models.CharField(max_length=32)),
                ('elevation', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='breadcrumb',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Product'),
        ),
    ]
